POST http://d8e9f6ad-4112-4417-97c0-01b4246b284a.japaneast.azurecontainer.io/score
Content-Type: application/json
Authorization: Bearer sYDHOfPPfLTb0w5gDucnNQfT8VinfhBf

{"data": [{"age": 17, "job": "blue-collar", "marital": "married", "education": "university.degree", "default": "no", "housing": "yes", "loan": "yes", "contact": "cellular", "month": "may", "day_of_week": "mon", "duration": 971, "campaign": 1, "pdays": 999, "previous": 1, "poutcome": "failure", "emp.var.rate": -1.8, "cons.price.idx": 92.893, "cons.conf.idx": -46.2, "euribor3m": 1.299, "nr.employed": 5099.1}, {"age": 87, "job": "blue-collar", "marital": "married", "education": "university.degree", "default": "no", "housing": "yes", "loan": "yes", "contact": "cellular", "month": "may", "day_of_week": "mon", "duration": 471, "campaign": 1, "pdays": 999, "previous": 1, "poutcome": "failure", "emp.var.rate": -1.8, "cons.price.idx": 92.893, "cons.conf.idx": -46.2, "euribor3m": 1.299, "nr.employed": 5099.1}]}